version: "3"
services:

  redis:
    image: redis:latest
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
    networks:
      - frontend
      - backend
    command: redis-server /usr/local/etc/redis/redis.conf
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - frontend
      - backend
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure

  web:
    image: kensh/thumbnail_web:0.1
    volumes: 
      - upload:/opt/thumbnail/upload
    ports:
      - "80:3000"
    networks:
      - frontend
    depends_on:
      - redis
      - rabbitmq
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure

  worker:
    image: kensh/thumbnail_worker:0.1
    volumes: 
      - upload:/opt/thumbnail/upload
    networks:
      - backend
    depends_on:
      - redis
      - rabbitmq
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure

networks:
  frontend:
  backend:

volumes:
  upload:
